[2025-10-30T17:58:58.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T17:58:58.542+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:58:52.933586+00:00 [queued]>
[2025-10-30T17:58:58.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:58:52.933586+00:00 [queued]>
[2025-10-30T17:58:58.556+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T17:58:58.573+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-30 17:58:52.933586+00:00
[2025-10-30T17:58:58.585+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2949) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T17:58:58.587+0000] {standard_task_runner.py:63} INFO - Started process 2963 to run task
[2025-10-30T17:58:58.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'manual__2025-10-30T17:58:52.933586+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmpk40mjca8']
[2025-10-30T17:58:58.589+0000] {standard_task_runner.py:91} INFO - Job 334: Subtask predict_and_log
[2025-10-30T17:58:58.646+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:58:52.933586+00:00 [running]> on host adac321c4d0a
[2025-10-30T17:58:58.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T17:58:52.933586+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T17:58:52.933586+00:00'
[2025-10-30T17:58:58.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T17:58:58.774+0000] {logging_mixin.py:188} INFO - ℹ️ Row already processed.
[2025-10-30T17:58:58.807+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-30T17:58:58.809+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T17:58:58.822+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=manual__2025-10-30T17:58:52.933586+00:00, execution_date=20251030T175852, start_date=20251030T175858, end_date=20251030T175858
[2025-10-30T17:58:58.883+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T17:58:58.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
