[2025-10-30T17:52:02.470+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T17:52:02.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:51:58.512703+00:00 [queued]>
[2025-10-30T17:52:02.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:51:58.512703+00:00 [queued]>
[2025-10-30T17:52:02.498+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T17:52:02.510+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-30 17:51:58.512703+00:00
[2025-10-30T17:52:02.517+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'manual__2025-10-30T17:51:58.512703+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp6bl6h1ql']
[2025-10-30T17:52:02.517+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2250) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T17:52:02.518+0000] {standard_task_runner.py:91} INFO - Job 306: Subtask predict_and_log
[2025-10-30T17:52:02.519+0000] {standard_task_runner.py:63} INFO - Started process 2257 to run task
[2025-10-30T17:52:02.562+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log manual__2025-10-30T17:51:58.512703+00:00 [running]> on host adac321c4d0a
[2025-10-30T17:52:02.633+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T17:51:58.512703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T17:51:58.512703+00:00'
[2025-10-30T17:52:02.635+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T17:52:03.799+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-30T17:52:03.806+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-30T17:52:03.815+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-10-30T17:52:04.210+0000] {logging_mixin.py:188} INFO - üèÉ View run LivePrediction_2025-10-30 17:52:03 at: http://mlflow:5000/#/experiments/1/runs/325d722f27cd4638b6b238937bca75ab
[2025-10-30T17:52:04.211+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/1
[2025-10-30T17:52:04.291+0000] {logging_mixin.py:188} INFO - ‚úÖ Prediction generated and pushed for logging.
[2025-10-30T17:52:04.293+0000] {python.py:237} INFO - Done. Returned value was: Prediction_Completed
[2025-10-30T17:52:04.294+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T17:52:04.311+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=manual__2025-10-30T17:51:58.512703+00:00, execution_date=20251030T175158, start_date=20251030T175202, end_date=20251030T175204
[2025-10-30T17:52:04.341+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T17:52:04.363+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T17:52:04.366+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
