[2025-10-30T14:40:03.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-30T14:40:03.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-30T14:35:00+00:00 [queued]>
[2025-10-30T14:40:03.665+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-30T14:35:00+00:00 [queued]>
[2025-10-30T14:40:03.666+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-30T14:40:03.679+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): predict_and_log> on 2025-10-30 14:35:00+00:00
[2025-10-30T14:40:03.685+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flood_prediction_pipeline', 'predict_and_log', 'scheduled__2025-10-30T14:35:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/flood_prediction_dag.py', '--cfg-path', '/tmp/tmp8o_1_yxm']
[2025-10-30T14:40:03.685+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3042) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T14:40:03.687+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask predict_and_log
[2025-10-30T14:40:03.687+0000] {standard_task_runner.py:63} INFO - Started process 3049 to run task
[2025-10-30T14:40:03.723+0000] {task_command.py:426} INFO - Running <TaskInstance: flood_prediction_pipeline.predict_and_log scheduled__2025-10-30T14:35:00+00:00 [running]> on host 31ca9a0c8d51
[2025-10-30T14:40:03.788+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flood_prediction_pipeline' AIRFLOW_CTX_TASK_ID='predict_and_log' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T14:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T14:35:00+00:00'
[2025-10-30T14:40:03.790+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-30T14:40:03.817+0000] {logging_mixin.py:188} INFO - ℹ️ Row already processed.
[2025-10-30T14:40:03.836+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-30T14:40:03.837+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-30T14:40:03.844+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flood_prediction_pipeline, task_id=predict_and_log, run_id=scheduled__2025-10-30T14:35:00+00:00, execution_date=20251030T143500, start_date=20251030T144003, end_date=20251030T144003
[2025-10-30T14:40:03.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-30T14:40:03.884+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-30T14:40:03.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
